export const resources = [
  {
    topic: 'Arrays',
    category: 'DSA',
    subtopic: 'Fundamentals',
    video: { title: 'Striver DSA Arrays Playlist', url: 'https://www.youtube.com/playlist?list=PLZjZj07V7eJ8MNz8q8q8q8q8q8q8q8q8', source: 'Striver' },
    notes: { title: 'Java Arrays - Oracle Docs', url: 'https://docs.oracle.com/javase/tutorial/java/nutsandbolts/arrays.html' },
    practice: { title: 'LeetCode Array Section', url: 'https://leetcode.com/problem-list/array/', platform: 'LeetCode' },
    questions: {
      easy: [
        { title: 'Two Sum', url: 'https://leetcode.com/problems/two-sum/', platform: 'LeetCode' },
        { title: 'Best Time to Buy and Sell Stock', url: 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/', platform: 'LeetCode' },
      ],
      medium: [
        { title: '3Sum', url: 'https://leetcode.com/problems/3sum/', platform: 'LeetCode' },
        { title: 'Container With Most Water', url: 'https://leetcode.com/problems/container-with-most-water/', platform: 'LeetCode' },
      ],
      hard: [{ title: 'Trapping Rain Water', url: 'https://leetcode.com/problems/trapping-rain-water/', platform: 'LeetCode' }],
    },
    revision: 'Master two-pointer and prefix sum patterns.',
    order: 1,
  },
  {
    topic: 'Hashing',
    category: 'DSA',
    video: { title: 'Hashing - Kunal Kushwaha', url: 'https://www.youtube.com/watch?v=KLlXCFG5SgA', source: 'Kunal Kushwaha' },
    notes: { title: 'HashMap Java Docs', url: 'https://docs.oracle.com/javase/8/docs/api/java/util/HashMap.html' },
    practice: { title: 'CodeStudio Hashing', url: 'https://www.naukri.com/code360/problems/count-occurrences-of-each-element_8365445', platform: 'CodeStudio' },
    questions: {
      easy: [{ title: 'Contains Duplicate', url: 'https://leetcode.com/problems/contains-duplicate/', platform: 'LeetCode' }],
      medium: [{ title: 'Group Anagrams', url: 'https://leetcode.com/problems/group-anagrams/', platform: 'LeetCode' }],
      hard: [{ title: 'Subarray Sum Equals K', url: 'https://leetcode.com/problems/subarray-sum-equals-k/', platform: 'LeetCode' }],
    },
    revision: 'Frequency map template.',
    order: 2,
  },
  {
    topic: 'Binary Search',
    category: 'DSA',
    video: { title: 'Binary Search - Striver', url: 'https://www.youtube.com/watch?v=GU7Wwgveq3c', source: 'Striver' },
    notes: { title: 'Binary Search GFG', url: 'https://www.geeksforgeeks.org/binary-search/' },
    practice: { title: 'LeetCode Binary Search', url: 'https://leetcode.com/problem-list/binary-search/', platform: 'LeetCode' },
    questions: {
      easy: [{ title: 'Binary Search', url: 'https://leetcode.com/problems/binary-search/', platform: 'LeetCode' }],
      medium: [{ title: 'Search in Rotated Sorted Array', url: 'https://leetcode.com/problems/search-in-rotated-sorted-array/', platform: 'LeetCode' }],
      hard: [{ title: 'Median of Two Sorted Arrays', url: 'https://leetcode.com/problems/median-of-two-sorted-arrays/', platform: 'LeetCode' }],
    },
    revision: 'Lower bound / upper bound templates.',
    order: 3,
  },
  {
    topic: 'Linked List',
    category: 'DSA',
    video: { title: 'Linked List - Apna College', url: 'https://www.youtube.com/watch?v=Z95xQ5ToEB4', source: 'Apna College' },
    notes: { title: 'Linked List GFG', url: 'https://www.geeksforgeeks.org/data-structures/linked-list/' },
    practice: { title: 'Striver Linked List Sheet', url: 'https://takeuforward.org/data-structure/singly-linked-list-tutorials/', platform: 'Striver' },
    questions: {
      easy: [{ title: 'Reverse Linked List', url: 'https://leetcode.com/problems/reverse-linked-list/', platform: 'LeetCode' }],
      medium: [{ title: 'Add Two Numbers', url: 'https://leetcode.com/problems/add-two-numbers/', platform: 'LeetCode' }],
      hard: [{ title: 'Merge K Sorted Lists', url: 'https://leetcode.com/problems/merge-k-sorted-lists/', platform: 'LeetCode' }],
    },
    revision: 'Dummy node technique.',
    order: 4,
  },
  {
    topic: 'Stack',
    category: 'DSA',
    video: { title: 'Stack - CodeHelp', url: 'https://www.youtube.com/watch?v=wywhql3BHGI', source: 'CodeHelp' },
    notes: { title: 'Stack Java Docs', url: 'https://docs.oracle.com/javase/8/docs/api/java/util/Stack.html' },
    practice: { title: 'LeetCode Stack', url: 'https://leetcode.com/tag/stack/', platform: 'LeetCode' },
    questions: {
      easy: [{ title: 'Valid Parentheses', url: 'https://leetcode.com/problems/valid-parentheses/', platform: 'LeetCode' }],
      medium: [{ title: 'Daily Temperatures', url: 'https://leetcode.com/problems/daily-temperatures/', platform: 'LeetCode' }],
      hard: [{ title: 'Largest Rectangle in Histogram', url: 'https://leetcode.com/problems/largest-rectangle-in-histogram/', platform: 'LeetCode' }],
    },
    revision: 'Monotonic stack pattern.',
    order: 5,
  },
  {
    topic: 'Queue',
    category: 'DSA',
    video: { title: 'Queue - Kunal Kushwaha', url: 'https://www.youtube.com/watch?v=3Z9SMZHaVaQ', source: 'Kunal Kushwaha' },
    notes: { title: 'Queue GFG', url: 'https://www.geeksforgeeks.org/queue-data-structure/' },
    practice: { title: 'CodeStudio Queue', url: 'https://www.naukri.com/code360/problems/implement-queue-using-linked-list_8164305', platform: 'CodeStudio' },
    questions: {
      easy: [{ title: 'Implement Queue using Stacks', url: 'https://leetcode.com/problems/implement-queue-using-stacks/', platform: 'LeetCode' }],
      medium: [{ title: 'Number of Recent Calls', url: 'https://leetcode.com/problems/number-of-recent-calls/', platform: 'LeetCode' }],
      hard: [{ title: 'Sliding Window Maximum', url: 'https://leetcode.com/problems/sliding-window-maximum/', platform: 'LeetCode' }],
    },
    revision: 'BFS uses queue — remember template.',
    order: 6,
  },
  {
    topic: 'Trees',
    category: 'DSA',
    video: { title: 'Trees - Striver', url: 'https://www.youtube.com/playlist?list=PLZjZj07V7eJ8MNz8q8q8q8q8q8q8q8q8', source: 'Striver' },
    notes: { title: 'Binary Tree GFG', url: 'https://www.geeksforgeeks.org/binary-tree-data-structure/' },
    practice: { title: 'LeetCode Tree', url: 'https://leetcode.com/tag/tree/', platform: 'LeetCode' },
    questions: {
      easy: [{ title: 'Maximum Depth of Binary Tree', url: 'https://leetcode.com/problems/maximum-depth-of-binary-tree/', platform: 'LeetCode' }],
      medium: [{ title: 'Validate Binary Search Tree', url: 'https://leetcode.com/problems/validate-binary-search-tree/', platform: 'LeetCode' }],
      hard: [{ title: 'Serialize and Deserialize Binary Tree', url: 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/', platform: 'LeetCode' }],
    },
    revision: 'DFS preorder/inorder/postorder.',
    order: 7,
  },
  {
    topic: 'Heap',
    category: 'DSA',
    video: { title: 'Heap - Striver', url: 'https://www.youtube.com/watch?v=HqPJF2L5h9U', source: 'Striver' },
    notes: { title: 'PriorityQueue Java', url: 'https://docs.oracle.com/javase/8/docs/api/java/util/PriorityQueue.html' },
    practice: { title: 'LeetCode Heap', url: 'https://leetcode.com/tag/heap-priority-queue/', platform: 'LeetCode' },
    questions: {
      easy: [{ title: 'Kth Largest Element', url: 'https://leetcode.com/problems/kth-largest-element-in-an-array/', platform: 'LeetCode' }],
      medium: [{ title: 'Top K Frequent Elements', url: 'https://leetcode.com/problems/top-k-frequent-elements/', platform: 'LeetCode' }],
      hard: [{ title: 'Find Median from Data Stream', url: 'https://leetcode.com/problems/find-median-from-data-stream/', platform: 'LeetCode' }],
    },
    revision: 'Min-heap vs max-heap.',
    order: 8,
  },
  {
    topic: 'Graph',
    category: 'DSA',
    video: { title: 'Graph - Kunal Kushwaha', url: 'https://www.youtube.com/playlist?list=PLZUvNoYYSzpBJochimA1PTcnKwu7lUTjO', source: 'Kunal Kushwaha' },
    notes: { title: 'Graph GFG', url: 'https://www.geeksforgeeks.org/graph-data-structure-and-algorithms/' },
    practice: { title: 'Striver Graph Sheet', url: 'https://takeuforward.org/data-structure/graph-representation-learning/', platform: 'Striver' },
    questions: {
      easy: [{ title: 'Number of Islands', url: 'https://leetcode.com/problems/number-of-islands/', platform: 'LeetCode' }],
      medium: [{ title: 'Course Schedule', url: 'https://leetcode.com/problems/course-schedule/', platform: 'LeetCode' }],
      hard: [{ title: 'Word Ladder', url: 'https://leetcode.com/problems/word-ladder/', platform: 'LeetCode' }],
    },
    revision: 'BFS for shortest path unweighted.',
    order: 9,
  },
  {
    topic: 'Dynamic Programming',
    category: 'DSA',
    video: { title: 'DP - Striver', url: 'https://www.youtube.com/playlist?list=PLZjZj07V7eJ8MNz8q8q8q8q8q8q8q8q8', source: 'Striver' },
    notes: { title: 'DP GFG', url: 'https://www.geeksforgeeks.org/dynamic-programming/' },
    practice: { title: 'LeetCode DP', url: 'https://leetcode.com/tag/dynamic-programming/', platform: 'LeetCode' },
    questions: {
      easy: [{ title: 'Climbing Stairs', url: 'https://leetcode.com/problems/climbing-stairs/', platform: 'LeetCode' }],
      medium: [{ title: 'Longest Increasing Subsequence', url: 'https://leetcode.com/problems/longest-increasing-subsequence/', platform: 'LeetCode' }],
      hard: [{ title: 'Edit Distance', url: 'https://leetcode.com/problems/edit-distance/', platform: 'LeetCode' }],
    },
    revision: 'Memoization vs tabulation.',
    order: 10,
  },
  {
    topic: 'Java Syntax',
    category: 'JAVA',
    video: { title: 'Java Full Course - Kunal', url: 'https://www.youtube.com/playlist?list=PLZUvNoYYSzpBJochimA1PTcnKwu7lUTjO', source: 'Kunal Kushwaha' },
    notes: { title: 'Oracle Java Tutorial', url: 'https://docs.oracle.com/javase/tutorial/' },
    practice: { title: 'GFG Java Practice', url: 'https://practice.geeksforgeeks.org/explore?page=1&category[]=Java', platform: 'GFG' },
    questions: { easy: [{ title: 'Java Basics', url: 'https://www.geeksforgeeks.org/java/', platform: 'GFG' }], medium: [], hard: [] },
    revision: 'Syntax and variables.',
    order: 11,
  },
  {
    topic: 'OOP Java',
    category: 'JAVA',
    video: { title: 'OOP Java - Apna College', url: 'https://www.youtube.com/watch?v=6s0yqbWi45A', source: 'Apna College' },
    notes: { title: 'OOP Oracle', url: 'https://docs.oracle.com/javase/tutorial/java/concepts/' },
    practice: { title: 'OOP GFG Problems', url: 'https://practice.geeksforgeeks.org/problems/search-by-roll-number/1', platform: 'GFG' },
    questions: { easy: [], medium: [{ title: 'Design Patterns Intro', url: 'https://www.geeksforgeeks.org/software-design-patterns/', platform: 'GFG' }], hard: [] },
    revision: 'Four pillars of OOP.',
    order: 12,
  },
  {
    topic: 'DBMS',
    category: 'CORE',
    video: { title: 'DBMS - Apna College', url: 'https://www.youtube.com/playlist?list=PL2_aWZzGR9BW3WjMrd8sUfN0mr9kLUSoc', source: 'Apna College' },
    notes: { title: 'DBMS GFG', url: 'https://www.geeksforgeeks.org/dbms/' },
    practice: { title: 'DBMS Quiz', url: 'https://www.geeksforgeeks.org/quiz-100-questions-on-dbms-for-placement-preparation/', platform: 'GFG' },
    questions: { easy: [], medium: [], hard: [] },
    revision: 'ACID, normalization, indexing.',
    order: 13,
  },
  {
    topic: 'Operating Systems',
    category: 'CORE',
    video: { title: 'OS - Apna College', url: 'https://www.youtube.com/playlist?list=PL2_aWZzGR9BW3WjMrd8sUfN0mr9kLUSoc', source: 'Apna College' },
    notes: { title: 'OS GFG', url: 'https://www.geeksforgeeks.org/operating-systems/' },
    practice: { title: 'OS Interview Questions', url: 'https://www.geeksforgeeks.org/operating-systems/', platform: 'GFG' },
    questions: { easy: [], medium: [], hard: [] },
    revision: 'Process, thread, deadlock, paging.',
    order: 14,
  },
  {
    topic: 'Computer Networks',
    category: 'CORE',
    video: { title: 'CN - Kunal Kushwaha', url: 'https://www.youtube.com/playlist?list=PLZUvNoYYSzpBJochimA1PTcnKwu7lUTjO', source: 'Kunal Kushwaha' },
    notes: { title: 'CN GFG', url: 'https://www.geeksforgeeks.org/computer-network-tutorials/' },
    practice: { title: 'CN Quiz', url: 'https://www.geeksforgeeks.org/computer-networks/', platform: 'GFG' },
    questions: { easy: [], medium: [], hard: [] },
    revision: 'OSI model, TCP vs UDP, HTTP.',
    order: 15,
  },
  {
    topic: 'Resume & Placement',
    category: 'PLACEMENT',
    video: { title: 'Resume Tips - Striver', url: 'https://www.youtube.com/watch?v=ZSPZha40v8s', source: 'Striver' },
    notes: { title: 'SDE Sheet', url: 'https://takeuforward.org/interviews/strivers-sde-sheet-top-coding-interview-problems/' },
    practice: { title: 'LeetCode Interview', url: 'https://leetcode.com/explore/interview/card/top-interview-questions-easy/', platform: 'LeetCode' },
    questions: { easy: [], medium: [], hard: [] },
    revision: 'Resume + LinkedIn + GitHub polish.',
    order: 16,
  },
];
